#!/usr/bin/env ansible-playbook
---
- name: Subscribe all OpenShift Hosts to RHMAP Repositories
  hosts: rhmap-hosts
  roles: 
    - subscribe

- name: Install RHMAP Templates in this host
  hosts: localhost
  connection: local
  tasks:
     - name: Installing all the necessary templates
       yum: name={{ item }} state=present
       with_items: "{{ subscription_manager_templates }}"
       tags:
          - templates  

- name: Install both RHMAP Core and MBaaS
  roles: 
     - core
     - mbaas
